server:
  port: 8080

spring:
  application:
      name: mall
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update//开发的阶段使用update，生产环境使用validate
        dialect: org.hibernate.dialect.MySQLDialect
app:
  image-base-url: http://localhost:8081

